# Generated by Django 3.1 on 2020-08-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_name', models.CharField(max_length=200)),
                ('act_sub_name', models.CharField(max_length=200)),
                ('act_cat_name', models.CharField(max_length=200)),
            ],
        ),
    ]
