# Generated by Django 3.1 on 2020-08-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('us_id', models.IntegerField(primary_key=True, serialize=False)),
                ('us_des', models.TextField()),
            ],
        ),
    ]
